//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "metadata")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub page_count: i32,
    pub upload: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::literatures::Entity")]
    Literatures,
    #[sea_orm(has_many = "super::tag_metadata::Entity")]
    TagMetadata,
}

impl Related<super::literatures::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Literatures.def()
    }
}

impl Related<super::tag_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TagMetadata.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::tag_metadata::Relation::Tags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::tag_metadata::Relation::Metadata.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
