//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::literatures::Entity as Literatures;
pub use super::metadata::Entity as Metadata;
pub use super::tag_metadata::Entity as TagMetadata;
pub use super::tags::Entity as Tags;
pub use super::tasks::Entity as Tasks;
