//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::TagType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub r#type: TagType,
    #[sea_orm(column_type = "Text")]
    pub label: String,
    pub canonical_id: Option<i32>,
    pub ref_count: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tag_metadata::Entity")]
    TagMetadata,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::CanonicalId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
}

impl Related<super::tag_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TagMetadata.def()
    }
}

impl Related<super::metadata::Entity> for Entity {
    fn to() -> RelationDef {
        super::tag_metadata::Relation::Metadata.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::tag_metadata::Relation::Tags.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
