[service.image.thumbnail]
enabled = true
width = 200
height = 200
quality = 75.0

[database]
host = "localhost"
port = 5432
database = "manga_neon"
user = "postgres"
password = "ENTER YOU PASSWD IN HERE"

[service.net]
host = "127.0.0.1:6789"

[crawler]
semaphore = 15
storage = "ENTER YOU STORAGE DIRECTORY"
retry = { max_retries = 2, delay = 2, max_delay = 30 }

[crawler.image]
quality = 100.0
semaphore = 8
