//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "tag_type")]
pub enum TagType {
    #[sea_orm(string_value = "genre")]
    Genre,
    #[sea_orm(string_value = "artist")]
    Artist,
    #[sea_orm(string_value = "origin")]
    Origin,
    #[sea_orm(string_value = "serial")]
    Serial,
    #[sea_orm(string_value = "character")]
    Character,
    #[sea_orm(string_value = "lang")]
    Lang,
    #[sea_orm(string_value = "group")]
    Group,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "task_status")]
pub enum TaskStatus {
    #[sea_orm(string_value = "success")]
    Success,
    #[sea_orm(string_value = "processing")]
    Processing,
    #[sea_orm(string_value = "failure")]
    Failure,
}
